#!/bin/sh
#cppcomp=i686-w64-mingw32-g++
#cppcomp64=x86_64-w64-mingw32-g++
cppcomp=i686-w64-mingw32-clang++
cppld=i686-w64-mingw32-ld
subdir1=`dirname $PWD`
subdir0=`dirname $subdir1`
splice=splice
thisdir=${subdir1##*/}

splicedir=$subdir0/$splice
spliceobjdir=$splicedir/obj
win=$HOME/.wine/drive_c
obj=$subdir1/obj
src=$PWD

cfsharedulink="-std=gnu++2a -fno-threadsafe-statics -static -static-libgcc -static-libstdc++ -I$splicedir -D_UNICODE -DUNICODE  -D_crt -mwindows -municode -s -O3 -fomit-frame-pointer -fno-ident -fno-asynchronous-unwind-tables -fdata-sections -ffunction-sections -nostdlib"
#options for standart linker
# -Wl,-Bstatic,-dll,-pic-executable,-disable-runtime-pseudo-reloc,--major-os-version,6,--minor-os-version,0,--major-image-version,6,--minor-image-versio,0,--major-subsystem-version,6,--minor-subsystem-version,0,-image-base=0x10000000,-dynamicbase,-nxcompat,-e_DllMainCRT@12,--disable-stdcall-fixup,--gc-sections"

cfsharedlibs="-lkernel32 -luser32 -lgdi32 -lpsapi -lwinmm -ldbghelp -lshell32 -lws2_32 -lntdll"

cd $obj
for i in "$@"
do
case $i in
    -c)
    $cppcomp -c $cfsharedulink -include-pch $obj/pch.h.gch $src/main.cpp $src/conv.cpp $src/memory.cpp $src/handle.cpp $src/stl.cpp 
    ;;
    -g|-gch)
    echo "generating pch.h.gch"
    $cppcomp $cfsharedulink -x c++-header -o $obj/pch.h.gch -c $src/pch.cpp
    exit;
    ;;
    -w|-win)
    echo "initializing wine links for ulink"
    ln -s `$cppld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012 | grep -o -P '(?<=DIR\(\").*(?=\"\))'` $win/mingw32lib
    ln -s $splicedir $win
    ln -s $subdir1/extra $win
    exit;
    ;;
    *)
            # unknown option
    ;;
esac
done
#compile only frequently changing source if no options specified
$cppcomp -c $cfsharedulink -include-pch $obj/pch.h.gch $src/app.cpp $src/feardata.cpp 
obj=C:/$thisdir/obj
bin=C:/$thisdir/bin
extra=C:/extra
spliceobjdir=C:/$splice/obj

cd $src
#ulink from officical ftp site won't work with latest wine. So i provide patched version.
#official ftp site: ftp://ftp.styx.cabel.net/pub/UniLink/
WINEDEBUG=-all wine $extra/ulink.exe -ZO"$bin/StringEditRuntime.dll" --gcc -e_DllMainCRT@12 -q -Z- -ZX- -W5.1 -U5.1 -V5.1 -S:0x1000 -Sc:0x1000 -H:0x10000 -Hc:0x0 -GF:NXCOMPAT -Gh -Gz -GS:*=*  -Tpd -q -B- -b* -N -LC:/extra -LC:/mingw32lib $obj/app.o $obj/handle.o $obj/feardata.o $obj/main.o $obj/conv.o $spliceobjdir/splicealloc.o $spliceobjdir/dizahex.o $spliceobjdir/splice.o $obj/memory.o $spliceobjdir/tramp.o $obj/stl.o $extra/msvcrt.lib $cfsharedlibs export.def 
